### ISSUE TITLE
Rope bridge stack check, off-by-one error, poor documentation

### ISSUE THREAD

**Issue by tofof** [DaedalusGame/BetterWithAddons#99]
Crossposted from [this BetterWithMods issue](https://github.com/BetterWithMods/BetterWithMods/issues/848). 

0) Bad Nomenclature
Please consider improving your documentation so that the manual containing features of your mod is not named for a different mod, in this case the "Better With Mods Manual".

1) Only one stack is checked
If you are attempting to span an 7-block gap with rope bridge and have, say, 10 stacks of 6 rope each, a rope will not connect despite having enough rope in your inventory.

2) Off-by-one error
2a) If you If you attempt to span a 7-block gap with rope already tied to each fencepost using a stack of 8 rope, 7 are consumed and 1 is left behind (as expected).
2b) However, using a stack of 7 rope to span the same gap -- rope will not connect despite having enough rope and it being all in one stack.

3) No error message
No error is given (contrast with e.g. the windmill and waterwheel that give their requirements when failing) when rope fails to connect. For consistency, please consider adding something to the effect of "no suitable post within 10 tiles at same height was found" 

4) Bad documentation
The documentation fails to mention that the maximum span of a rope bridge is a gap of 8 blocks between fence posts (making the rope bridge basically worthless except to span the most trivial of streams). 

5) Really, 8 blocks only?
Please consider increasing the distance to, say, 64 or making the maximum span a config variable.
It's sad when you want to use a mod's features and then get disappointed that they don't work.

**Comment by DaedalusGame** [comment]
0) If you haven't noticed this is an addon for Better With Mods
1) funky, will investigate, probably done for simplicity and never changed it
2) there's a lot more wrong with this one
3) can do
4) lets leave the numerics up to players to discover
5) another one-off, it's supposed to be 9 blocks and even that number is just a random pick because 9 blocks is actually a lot of distance! I'll have a look at extending the limit but not to 64 blocks :p and I'll add a config.

**Comment by tofof** [comment]
Thanks for addressing each point.
